"""rename_table

Revision ID: 080ba88a7dfe
Revises: 
Create Date: 2026-03-09 14:21:12.269287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '080ba88a7dfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Encomenda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Text(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('dono', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Encomenda_chat_id'), 'Encomenda', ['chat_id'], unique=False)
    op.create_index(op.f('ix_Encomenda_data'), 'Encomenda', ['data'], unique=False)
    op.create_index('ix_encomendas_chat_id_data', 'Encomenda', ['chat_id', 'data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_encomendas_chat_id_data', table_name='Encomenda')
    op.drop_index(op.f('ix_Encomenda_data'), table_name='Encomenda')
    op.drop_index(op.f('ix_Encomenda_chat_id'), table_name='Encomenda')
    op.drop_table('Encomenda')
    # ### end Alembic commands ###
