"""voltar_encomendas

Revision ID: b4c28da2364a
Revises: 080ba88a7dfe
Create Date: 2026-03-09 14:35:22.198990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4c28da2364a'
down_revision: Union[str, Sequence[str], None] = '080ba88a7dfe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encomendas_chat_id_data'), table_name='Encomenda')
    op.drop_index(op.f('ix_Encomenda_data'), table_name='Encomenda')
    op.drop_index(op.f('ix_Encomenda_chat_id'), table_name='Encomenda')
    op.drop_table('Encomenda')
    op.create_table('encomendas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('item', sa.Text(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('dono', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encomendas_chat_id'), 'encomendas', ['chat_id'], unique=False)
    op.create_index('ix_encomendas_chat_id_data', 'encomendas', ['chat_id', 'data'], unique=False)
    op.create_index(op.f('ix_encomendas_data'), 'encomendas', ['data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encomendas_data'), table_name='encomendas')
    op.drop_index('ix_encomendas_chat_id_data', table_name='encomendas')
    op.drop_index(op.f('ix_encomendas_chat_id'), table_name='encomendas')
    op.drop_table('encomendas')
    op.create_table('Encomenda',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('data', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('dono', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('Encomenda_pkey'))
    )
    op.create_index(op.f('ix_encomendas_chat_id_data'), 'Encomenda', ['chat_id', 'data'], unique=False)
    op.create_index(op.f('ix_Encomenda_data'), 'Encomenda', ['data'], unique=False)
    op.create_index(op.f('ix_Encomenda_chat_id'), 'Encomenda', ['chat_id'], unique=False)
    # ### end Alembic commands ###
